"""Versioned, purpose-specific CSV contracts for RL training logs."""

from __future__ import annotations

import csv


RL_LOG_SCHEMA_VERSION = 44


# One row per training iteration. This is the promotion/strength dashboard source,
# not a copy of replay and profiler telemetry.
RL_MAIN_COLUMNS = (
    "iteration", "schema_version",
    "avg_loss", "policy_loss", "value_loss",
    "value_primary_loss", "value_scalar_aux_loss", "moves_left_loss",
    "search_q_loss", "search_q_coverage", "search_q_mae",
    "learning_rate", "value_loss_weight",
    "temperature", "policy_top1_acc", "policy_top3_acc",
    "policy_correction_loss", "policy_correction_rank_loss",
    "policy_correction_rank_weight",
    "policy_correction_top1_acc",
    "policy_correction_fraction", "policy_correction_weight_share",
    "correction_audit_rows",
    "correction_audit_top1_before", "correction_audit_top1_after",
    "correction_audit_top1_gain",
    "correction_audit_rank_before", "correction_audit_rank_after",
    "correction_audit_rank_gain",
    "correction_audit_target_probability_before",
    "correction_audit_target_probability_after",
    "correction_audit_target_probability_gain",
    "correction_audit_logit_margin_before", "correction_audit_logit_margin_after",
    "correction_audit_logit_margin_gain",
    "correction_audit_retention", "correction_audit_retention_rows",
    "grad_total_norm", "grad_clip_fraction", "grad_clip_scale_mean",
    "grad_backbone_norm", "grad_policy_head_norm", "grad_value_head_norm",
    "grad_policy_probe_norm", "grad_value_probe_norm", "grad_policy_value_cosine",
    "value_mae", "value_wdl_acc", "value_wdl_brier", "value_wdl_ece",
    "value_pred_win_probability", "value_pred_draw_probability", "value_pred_loss_probability",
    "value_target_win_fraction", "value_target_draw_fraction", "value_target_loss_fraction",
    "value_draw_probability_opening", "value_draw_probability_middlegame",
    "value_draw_probability_endgame", "value_draw_target_fraction_opening",
    "value_draw_target_fraction_middlegame", "value_draw_target_fraction_endgame",
    "value_error_priority_fraction", "value_error_priority_weight_share",
    "value_error_priority_mae",
    "value_prediction_mean", "value_target_mean", "value_mean_bias",
    "value_root_q_pred_mean", "value_root_q_target_mean",
    "value_root_q_bias", "value_root_q_mae", "value_root_q_correlation",
    "value_mae_opening", "value_mae_middlegame", "value_mae_endgame",
    "value_std_ratio_opening", "value_std_ratio_middlegame", "value_std_ratio_endgame",
    "eval_stage", "eval_games", "eval_wins", "eval_draws", "eval_losses", "eval_unresolved",
    "score_rate", "true_win_rate", "eval_score_lower_bound",
    "eval_score_rate_ema", "eval_true_win_rate_ema",
    "no_mcts_games", "no_mcts_score_rate", "no_mcts_win_rate",
    "no_mcts_score_lower_bound", "mcts_no_mcts_gap",
    "eval_mcts_move_samples", "eval_mcts_avg_simulations", "eval_mcts_reduced_budget_rate",
    "eval_mcts_changed_rate",
    "eval_mcts_higher_q_when_changed_rate", "eval_mcts_lower_q_when_changed_rate",
    "eval_mcts_changed_q_delta_mean",
    "eval_reference_mcts_avg_simulations", "eval_reference_mcts_reduced_budget_rate",
    "eval_reference_mcts_changed_rate", "eval_reference_mcts_higher_q_when_changed_rate",
    "anchor_games", "anchor_score_rate", "anchor_true_win_rate", "anchor_score_lower_bound",
    "anchor_no_mcts_games", "anchor_no_mcts_score_rate", "anchor_no_mcts_score_lower_bound",
    "anchor_mcts_no_mcts_gap",
    "rl_best_model", "best_iteration",
    "estimated_elo_nn", "estimated_elo_nn_se", "estimated_elo_nn_ci95_low",
    "estimated_elo_nn_ci95_high", "estimated_elo_mcts", "estimated_elo_mcts_se",
    "estimated_elo_mcts_ci95_low", "estimated_elo_mcts_ci95_high",
    "estimated_elo_mcts_simulations", "estimated_elo_mcts_by_simulations",
)


# Replay, target and search behaviour. Evaluation and profiler fields intentionally
# do not live here; their canonical homes are the main and performance CSVs.
RL_DATA_QUALITY_COLUMNS = (
    "iteration", "schema_version", "timestamp",
    "positions_added", "replay_candidate_positions", "played_positions",
    "replay_cap_dropped_positions", "replay_overwritten_positions",
    "replay_resize_dropped_positions", "replay_evicted_positions_total",
    "replay_size", "replay_capacity", "replay_fill_rate",
    "train_batch_size", "train_steps", "train_selected_samples", "train_replay_coverage",
    "train_replay_passes",
    "champion_replay_size", "champion_replay_capacity", "champion_replay_added",
    "champion_replay_selected_samples", "champion_replay_selected_fraction",
    "champion_replay_target_fraction",
    "replay_decisive_fraction", "replay_draw_fraction", "replay_value_mean",
    "replay_value_std", "replay_value_positive_fraction", "replay_value_neutral_fraction",
    "replay_value_negative_fraction", "replay_value_skew",
    "policy_weight_mean", "policy_weight_p10", "policy_weight_low_fraction",
    "value_weight_mean", "value_weight_p10", "value_weight_low_fraction",
    "root_q_coverage", "root_q_mean", "root_q_std",
    "best_q_coverage", "best_q_mean", "played_q_coverage", "orig_q_coverage",
    "policy_kld_coverage", "policy_kld_mean", "deblunder_value_fraction",
    "replay_source_learner_fraction", "replay_source_frozen_best_fraction",
    "replay_policy_weight_learner_share", "replay_policy_weight_frozen_best_share",
    "policy_target_len_mean", "policy_target_len_p90", "policy_target_entropy_mean",
    "policy_target_top1_prob_mean", "policy_target_top3_prob_mean",
    "policy_target_effective_moves", "policy_entropy_ratio",
    "replay_policy_correction_fraction", "replay_policy_correction_q_delta_mean",
    "replay_policy_correction_weight_share",
    "train_policy_correction_sharpened_fraction",
    "train_policy_correction_target_top1_before",
    "train_policy_correction_target_top1_after",
    "correction_audit_rows",
    "correction_audit_top1_before", "correction_audit_top1_after",
    "correction_audit_top1_gain",
    "correction_audit_rank_before", "correction_audit_rank_after",
    "correction_audit_rank_gain",
    "correction_audit_target_probability_before",
    "correction_audit_target_probability_after",
    "correction_audit_target_probability_gain",
    "correction_audit_logit_margin_before", "correction_audit_logit_margin_after",
    "correction_audit_logit_margin_gain",
    "correction_audit_retention", "correction_audit_retention_rows",
    "reanalyse_selected", "reanalyse_updated", "reanalyse_correction_fraction",
    "sample_age_avg", "sample_age_p50", "sample_age_p90", "sample_age_new_fraction",
    "sample_age_le1_fraction", "iterations_since_promotion",
    "recent_sample_age_avg", "recent_sample_age_p50", "recent_sample_age_p90",
    "recent_sample_age_new_fraction", "recent_sample_age_le1_fraction",
    "champion_sample_age_avg", "champion_sample_age_p50", "champion_sample_age_p90",
    "selfplay_completed_games", "selfplay_draw_rate", "selfplay_decisive_rate",
    "selfplay_auto_draw_rate", "selfplay_truncated_rate", "selfplay_avg_game_value",
    "selfplay_value_std", "selfplay_replay_storage_keep_rate",
    "selfplay_hard_start_games", "selfplay_hard_start_fraction",
    "opponent_current_planned_share", "opponent_current_actual_share",
    "opponent_current_games", "opponent_current_score_rate",
    "opponent_best_planned_share", "opponent_best_actual_share",
    "opponent_best_games", "opponent_best_score_rate", "opponent_mix_error",
    "opponent_promotion_transition_progress",
    "mcts_avg_sims", "mcts_fresh_sims", "mcts_inherited_visit_credit",
    "mcts_avg_budget",
    "mcts_budget_utilization", "mcts_budget_target", "mcts_budget_min",
    "mcts_budget_p10", "mcts_budget_p50", "mcts_budget_p90", "mcts_budget_max",
    "mcts_difficulty_mean", "mcts_difficulty_budget_correlation",
    "mcts_tree_reuse_hit_rate", "mcts_tree_inherited_visits_avg",
    "mcts_tree_reuse_credit_samples", "mcts_tree_reuse_credit_fraction",
    "mcts_tree_reuse_quality_avg", "mcts_tree_reuse_candidate_coverage_avg",
    "mcts_tree_reuse_visited_prior_mass_avg", "mcts_tree_reuse_fresh_floor_avg",
    "mcts_tree_reuse_scout_stability_avg", "mcts_tree_reuse_scout_extra_credit_avg",
    "mcts_tree_reuse_scout_reduction_rate",
    "mcts_shared_tree_search_fraction",
    "mcts_prior_agreement_rate", "mcts_prior_changed_rate",
    "mcts_changed_opening_rate", "mcts_changed_middlegame_rate",
    "mcts_changed_endgame_rate", "mcts_useful_change_rate", "mcts_harmful_change_rate",
    "mcts_changed_to_higher_q_rate", "mcts_changed_to_lower_q_when_changed_rate",
    "mcts_changed_q_delta_mean", "mcts_changed_q_delta_p10", "mcts_changed_q_delta_p90",
    "mcts_policy_kl_mean", "mcts_top_visit_prob_mean", "mcts_visit_gap_mean",
    "mcts_visit_entropy_mean", "mcts_good_target_rate", "mcts_explored_prior_mass_mean",
    "mcts_visited_move_count_mean", "mcts_legal_move_count_mean",
    "mcts_visit_coverage_ratio_mean",
)


# Throughput and bottleneck diagnosis. A completed MCTS simulation/visit is
# deliberately separate from root->leaf selection traversals and NN leaf
# evaluations. Replay positions are the retained subset of played positions.
RL_PERFORMANCE_COLUMNS = (
    "iteration", "schema_version", "timestamp",
    "selfplay_worker_count", "selfplay_games_per_worker_mean",
    "selfplay_games_per_worker_min", "selfplay_games_per_worker_max",
    "selfplay_games_per_worker_std", "selfplay_worker_finish_spread_s",
    "selfplay_tail_10pct_time_s", "selfplay_global_game_stream_enabled",
    "replay_positions_per_sec", "played_positions_per_sec",
    "mcts_simulations_per_sec", "mcts_effective_simulations_per_sec",
    "mcts_nn_evaluations_per_sec",
    "mcts_selection_node_traversals_per_sec",
    "iteration_total_time_s", "bottleneck_stage",
    "stage_setup_time_s", "stage_selfplay_time_s", "stage_replay_time_s",
    "stage_train_time_s", "stage_regular_eval_time_s", "stage_promotion_eval_time_s",
    "stage_reanalyse_time_s",
    "stage_elo_eval_time_s", "stage_log_time_s", "stage_checkpoint_time_s",
    "stage_gc_time_s", "avg_game_length",
    "mcts_avg_batch_size", "mcts_central_avg_batch_size", "mcts_worker_nn_wait_share_pct",
    "central_remote_wait_ms_per_request", "central_request_submit_ms_per_request",
    "central_server_queue_wait_ms_per_request",
    "central_descriptor_queue_wait_ms_per_request",
    "central_batch_coalesce_wait_ms_per_request",
    "central_server_pipeline_wait_ms_per_request",
    "central_server_output_finalize_wait_ms_per_request",
    "central_server_concat_ms_per_request", "central_server_h2d_ms_per_request",
    "central_server_forward_ms_per_request", "central_server_d2h_ms_per_request",
    "central_server_other_ms_per_request", "central_worker_ipc_ms_per_request",
    "central_server_total_ms_per_request",
    "central_shared_memory_request_fraction", "central_shared_memory_mib_avoided",
    "central_shared_slot_wait_ms_per_request",
    "central_cache_hit_rate", "central_dedup_hit_rate", "central_nn_saved_rate",
    "central_cache_active_fraction", "central_nn_saved_overall_rate",
    "central_cache_suspensions", "central_cache_reactivations",
    "central_nn_evaluated_positions",
    "central_server_cache_lookup_ms_per_request",
    "central_server_staging_copy_ms_per_request", "central_gpu_batch_fill",
    "central_batch_target_avg", "central_output_pipeline_rate",
    "central_auto_batch_calibrated_rate",
    "mcts_worker_nn_wait_ms_per_position", "mcts_worker_nn_wait_ms_per_batch",
    "central_server_queue_wait_ms_per_position", "central_server_forward_ms_per_position",
    "central_server_total_ms_per_position",
    "mcts_search_many_time_s", "mcts_nn_inference_time_s", "mcts_nn_inference_calls",
    "mcts_nn_inference_batch_items", "mcts_avg_legal_moves_per_position",
    "result_queue_wait_ms", "mcts_search_root_setup_time_s", "mcts_search_selection_time_s", "mcts_search_backprop_time_s",
    "mcts_native_tree_expand_sync_time_s", "mcts_native_tree_backup_time_s",
    "mcts_native_tree_import_time_s", "mcts_native_tree_sync_time_s",
    "mcts_native_tree_selection_batches", "mcts_native_tree_backup_batches",
    "mcts_native_tree_selected_leaves", "mcts_python_tree_selected_leaves",
    "mcts_native_tree_selection_rate", "mcts_native_tree_import_nodes",
    "mcts_native_tree_import_edges", "mcts_native_tree_fallbacks",
    "mcts_search_metadata_time_s", "mcts_native_root_selection_calls", "mcts_python_root_selection_calls",
    "mcts_native_root_selection_rate", "mcts_native_completed_q_calls",
    "mcts_python_completed_q_calls", "mcts_native_completed_q_rate",
    "mcts_batch_expand_dedup_time_s", "mcts_batch_expand_eval_time_s",
    "mcts_batch_expand_eval_calls", "mcts_board_materialize_time_s", "mcts_terminal_checks_time_s",
    "mcts_board_to_tensor_time_s",
    "mcts_batch_expand_legal_moves_time_s", "mcts_batch_expand_move_index_time_s",
    "mcts_batch_expand_tensor_pack_time_s",
    "mcts_batch_expand_history_time_s", "mcts_batch_expand_input_pack_time_s",
    "mcts_batch_expand_legal_index_pack_time_s", "mcts_batch_expand_cpu_policy_time_s",
    "mcts_batch_expand_value_fanout_time_s", "mcts_policy_target_build_time_s",
    "mcts_move_selection_time_s", "mcts_adjudication_time_s", "mcts_syzygy_time_s",
)


def csv_row(columns, record):
    """Return a schema-ordered row while normalising missing values."""
    return ["" if record.get(column) is None else record.get(column, "") for column in columns]


def append_csv_record(path, columns, record):
    with open(path, "a", newline="") as handle:
        csv.writer(handle).writerow(csv_row(columns, record))
